# Generated by Django 4.1.2 on 2023-06-29 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='direccionpedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
