# Generated by Django 4.1.2 on 2023-06-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumno',
            new_name='Usuario',
        ),
    ]
